import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col bg-slate-950 text-slate-100">
        <nav className="bg-slate-900 border-b border-slate-800 shadow-sm">
          <ul className="mx-auto flex max-w-6xl items-center gap-4 px-4 py-3 text-sm font-medium sm:px-6">
            <Link href="/" className="rounded-md px-3 py-2 text-slate-200 transition hover:bg-slate-800 hover:text-white">Users</Link>
            <Link href="/users/add" className="rounded-md px-3 py-2 text-slate-200 transition hover:bg-slate-800 hover:text-white">Add User</Link>
          </ul>
        </nav>
        {children}

      </body>
    </html>
  );
}
