export interface CityEntry {
  city: string;
  country: string;
}

export const CITIES: CityEntry[] = [
  { city: "Kabul", country: "Afghanistan" },
  { city: "Herat", country: "Afghanistan" },
  { city: "Tirana", country: "Albania" },
  { city: "Vlorë", country: "Albania" },
  { city: "Algiers", country: "Algeria" },
  { city: "Oran", country: "Algeria" },
  { city: "Andorra la Vella", country: "Andorra" },
  { city: "Luanda", country: "Angola" },
  { city: "Buenos Aires", country: "Argentina" },
  { city: "Mendoza", country: "Argentina" },
  { city: "Bariloche", country: "Argentina" },
  { city: "Córdoba", country: "Argentina" },
  { city: "Yerevan", country: "Armenia" },
  { city: "Gyumri", country: "Armenia" },
  { city: "Dilijan", country: "Armenia" },
  { city: "Sydney", country: "Australia" },
  { city: "Melbourne", country: "Australia" },
  { city: "Brisbane", country: "Australia" },
  { city: "Perth", country: "Australia" },
  { city: "Gold Coast", country: "Australia" },
  { city: "Vienna", country: "Austria" },
  { city: "Salzburg", country: "Austria" },
  { city: "Innsbruck", country: "Austria" },
  { city: "Baku", country: "Azerbaijan" },
  { city: "Ganja", country: "Azerbaijan" },
  { city: "Nassau", country: "Bahamas" },
  { city: "Manama", country: "Bahrain" },
  { city: "Dhaka", country: "Bangladesh" },
  { city: "Chittagong", country: "Bangladesh" },
  { city: "Bridgetown", country: "Barbados" },
  { city: "Minsk", country: "Belarus" },
  { city: "Brussels", country: "Belgium" },
  { city: "Bruges", country: "Belgium" },
  { city: "Antwerp", country: "Belgium" },
  { city: "Ghent", country: "Belgium" },
  { city: "Belize City", country: "Belize" },
  { city: "Cotonou", country: "Benin" },
  { city: "Thimphu", country: "Bhutan" },
  { city: "Paro", country: "Bhutan" },
  { city: "La Paz", country: "Bolivia" },
  { city: "Sucre", country: "Bolivia" },
  { city: "Sarajevo", country: "Bosnia and Herzegovina" },
  { city: "Mostar", country: "Bosnia and Herzegovina" },
  { city: "Gaborone", country: "Botswana" },
  { city: "Rio de Janeiro", country: "Brazil" },
  { city: "São Paulo", country: "Brazil" },
  { city: "Salvador", country: "Brazil" },
  { city: "Brasília", country: "Brazil" },
  { city: "Bandar Seri Begawan", country: "Brunei" },
  { city: "Sofia", country: "Bulgaria" },
  { city: "Plovdiv", country: "Bulgaria" },
  { city: "Ouagadougou", country: "Burkina Faso" },
  { city: "Bujumbura", country: "Burundi" },
  { city: "Phnom Penh", country: "Cambodia" },
  { city: "Siem Reap", country: "Cambodia" },
  { city: "Yaoundé", country: "Cameroon" },
  { city: "Douala", country: "Cameroon" },
  { city: "Toronto", country: "Canada" },
  { city: "Vancouver", country: "Canada" },
  { city: "Montreal", country: "Canada" },
  { city: "Calgary", country: "Canada" },
  { city: "Quebec City", country: "Canada" },
  { city: "N'Djamena", country: "Chad" },
  { city: "Santiago", country: "Chile" },
  { city: "Valparaíso", country: "Chile" },
  { city: "Beijing", country: "China" },
  { city: "Shanghai", country: "China" },
  { city: "Hong Kong", country: "China" },
  { city: "Xi'an", country: "China" },
  { city: "Guangzhou", country: "China" },
  { city: "Bogotá", country: "Colombia" },
  { city: "Cartagena", country: "Colombia" },
  { city: "Medellín", country: "Colombia" },
  { city: "San José", country: "Costa Rica" },
  { city: "Tamarindo", country: "Costa Rica" },
  { city: "Zagreb", country: "Croatia" },
  { city: "Dubrovnik", country: "Croatia" },
  { city: "Split", country: "Croatia" },
  { city: "Havana", country: "Cuba" },
  { city: "Varadero", country: "Cuba" },
  { city: "Nicosia", country: "Cyprus" },
  { city: "Limassol", country: "Cyprus" },
  { city: "Prague", country: "Czech Republic" },
  { city: "Brno", country: "Czech Republic" },
  { city: "Český Krumlov", country: "Czech Republic" },
  { city: "Copenhagen", country: "Denmark" },
  { city: "Aarhus", country: "Denmark" },
  { city: "Odense", country: "Denmark" },
  { city: "Djibouti City", country: "Djibouti" },
  { city: "Santo Domingo", country: "Dominican Republic" },
  { city: "Punta Cana", country: "Dominican Republic" },
  { city: "Quito", country: "Ecuador" },
  { city: "Guayaquil", country: "Ecuador" },
  { city: "Cairo", country: "Egypt" },
  { city: "Luxor", country: "Egypt" },
  { city: "Alexandria", country: "Egypt" },
  { city: "San Salvador", country: "El Salvador" },
  { city: "Tallinn", country: "Estonia" },
  { city: "Tartu", country: "Estonia" },
  { city: "Addis Ababa", country: "Ethiopia" },
  { city: "Suva", country: "Fiji" },
  { city: "Nadi", country: "Fiji" },
  { city: "Helsinki", country: "Finland" },
  { city: "Tampere", country: "Finland" },
  { city: "Rovaniemi", country: "Finland" },
  { city: "Paris", country: "France" },
  { city: "Nice", country: "France" },
  { city: "Lyon", country: "France" },
  { city: "Marseille", country: "France" },
  { city: "Bordeaux", country: "France" },
  { city: "Libreville", country: "Gabon" },
  { city: "Tbilisi", country: "Georgia" },
  { city: "Batumi", country: "Georgia" },
  { city: "Kutaisi", country: "Georgia" },
  { city: "Berlin", country: "Germany" },
  { city: "Munich", country: "Germany" },
  { city: "Hamburg", country: "Germany" },
  { city: "Frankfurt", country: "Germany" },
  { city: "Cologne", country: "Germany" },
  { city: "Accra", country: "Ghana" },
  { city: "Kumasi", country: "Ghana" },
  { city: "Athens", country: "Greece" },
  { city: "Santorini", country: "Greece" },
  { city: "Mykonos", country: "Greece" },
  { city: "Crete", country: "Greece" },
  { city: "Guatemala City", country: "Guatemala" },
  { city: "Antigua", country: "Guatemala" },
  { city: "Conakry", country: "Guinea" },
  { city: "Georgetown", country: "Guyana" },
  { city: "Port-au-Prince", country: "Haiti" },
  { city: "Tegucigalpa", country: "Honduras" },
  { city: "Roatán", country: "Honduras" },
  { city: "Budapest", country: "Hungary" },
  { city: "Debrecen", country: "Hungary" },
  { city: "Reykjavik", country: "Iceland" },
  { city: "Akureyri", country: "Iceland" },
  { city: "Vik", country: "Iceland" },
  { city: "Mumbai", country: "India" },
  { city: "Delhi", country: "India" },
  { city: "Jaipur", country: "India" },
  { city: "Goa", country: "India" },
  { city: "Bangalore", country: "India" },
  { city: "Agra", country: "India" },
  { city: "Varanasi", country: "India" },
  { city: "Bali", country: "Indonesia" },
  { city: "Jakarta", country: "Indonesia" },
  { city: "Yogyakarta", country: "Indonesia" },
  { city: "Tehran", country: "Iran" },
  { city: "Isfahan", country: "Iran" },
  { city: "Shiraz", country: "Iran" },
  { city: "Baghdad", country: "Iraq" },
  { city: "Erbil", country: "Iraq" },
  { city: "Dublin", country: "Ireland" },
  { city: "Cork", country: "Ireland" },
  { city: "Galway", country: "Ireland" },
  { city: "Tel Aviv", country: "Israel" },
  { city: "Jerusalem", country: "Israel" },
  { city: "Haifa", country: "Israel" },
  { city: "Rome", country: "Italy" },
  { city: "Milan", country: "Italy" },
  { city: "Venice", country: "Italy" },
  { city: "Florence", country: "Italy" },
  { city: "Naples", country: "Italy" },
  { city: "Kingston", country: "Jamaica" },
  { city: "Montego Bay", country: "Jamaica" },
  { city: "Tokyo", country: "Japan" },
  { city: "Kyoto", country: "Japan" },
  { city: "Osaka", country: "Japan" },
  { city: "Sapporo", country: "Japan" },
  { city: "Hiroshima", country: "Japan" },
  { city: "Amman", country: "Jordan" },
  { city: "Petra", country: "Jordan" },
  { city: "Almaty", country: "Kazakhstan" },
  { city: "Astana", country: "Kazakhstan" },
  { city: "Nairobi", country: "Kenya" },
  { city: "Mombasa", country: "Kenya" },
  { city: "Kuwait City", country: "Kuwait" },
  { city: "Bishkek", country: "Kyrgyzstan" },
  { city: "Vientiane", country: "Laos" },
  { city: "Luang Prabang", country: "Laos" },
  { city: "Riga", country: "Latvia" },
  { city: "Beirut", country: "Lebanon" },
  { city: "Vilnius", country: "Lithuania" },
  { city: "Luxembourg City", country: "Luxembourg" },
  { city: "Antananarivo", country: "Madagascar" },
  { city: "Kuala Lumpur", country: "Malaysia" },
  { city: "Penang", country: "Malaysia" },
  { city: "Langkawi", country: "Malaysia" },
  { city: "Malé", country: "Maldives" },
  { city: "Bamako", country: "Mali" },
  { city: "Valletta", country: "Malta" },
  { city: "Port Louis", country: "Mauritius" },
  { city: "Mexico City", country: "Mexico" },
  { city: "Cancún", country: "Mexico" },
  { city: "Guadalajara", country: "Mexico" },
  { city: "Tulum", country: "Mexico" },
  { city: "Playa del Carmen", country: "Mexico" },
  { city: "Chișinău", country: "Moldova" },
  { city: "Monaco", country: "Monaco" },
  { city: "Ulaanbaatar", country: "Mongolia" },
  { city: "Podgorica", country: "Montenegro" },
  { city: "Kotor", country: "Montenegro" },
  { city: "Marrakech", country: "Morocco" },
  { city: "Casablanca", country: "Morocco" },
  { city: "Fez", country: "Morocco" },
  { city: "Chefchaouen", country: "Morocco" },
  { city: "Maputo", country: "Mozambique" },
  { city: "Yangon", country: "Myanmar" },
  { city: "Mandalay", country: "Myanmar" },
  { city: "Windhoek", country: "Namibia" },
  { city: "Kathmandu", country: "Nepal" },
  { city: "Pokhara", country: "Nepal" },
  { city: "Amsterdam", country: "Netherlands" },
  { city: "Rotterdam", country: "Netherlands" },
  { city: "Utrecht", country: "Netherlands" },
  { city: "Auckland", country: "New Zealand" },
  { city: "Queenstown", country: "New Zealand" },
  { city: "Wellington", country: "New Zealand" },
  { city: "Managua", country: "Nicaragua" },
  { city: "León", country: "Nicaragua" },
  { city: "Niamey", country: "Niger" },
  { city: "Lagos", country: "Nigeria" },
  { city: "Abuja", country: "Nigeria" },
  { city: "Skopje", country: "North Macedonia" },
  { city: "Oslo", country: "Norway" },
  { city: "Bergen", country: "Norway" },
  { city: "Tromsø", country: "Norway" },
  { city: "Muscat", country: "Oman" },
  { city: "Karachi", country: "Pakistan" },
  { city: "Lahore", country: "Pakistan" },
  { city: "Islamabad", country: "Pakistan" },
  { city: "Panama City", country: "Panama" },
  { city: "Port Moresby", country: "Papua New Guinea" },
  { city: "Asunción", country: "Paraguay" },
  { city: "Lima", country: "Peru" },
  { city: "Cusco", country: "Peru" },
  { city: "Arequipa", country: "Peru" },
  { city: "Manila", country: "Philippines" },
  { city: "Cebu", country: "Philippines" },
  { city: "Palawan", country: "Philippines" },
  { city: "Warsaw", country: "Poland" },
  { city: "Krakow", country: "Poland" },
  { city: "Gdańsk", country: "Poland" },
  { city: "Lisbon", country: "Portugal" },
  { city: "Porto", country: "Portugal" },
  { city: "Faro", country: "Portugal" },
  { city: "Doha", country: "Qatar" },
  { city: "Al Rayyan", country: "Qatar" },
  { city: "Bucharest", country: "Romania" },
  { city: "Brasov", country: "Romania" },
  { city: "Moscow", country: "Russia" },
  { city: "Saint Petersburg", country: "Russia" },
  { city: "Kazan", country: "Russia" },
  { city: "Kigali", country: "Rwanda" },
  { city: "Riyadh", country: "Saudi Arabia" },
  { city: "Jeddah", country: "Saudi Arabia" },
  { city: "Dakar", country: "Senegal" },
  { city: "Belgrade", country: "Serbia" },
  { city: "Novi Sad", country: "Serbia" },
  { city: "Victoria", country: "Seychelles" },
  { city: "Singapore", country: "Singapore" },
  { city: "Bratislava", country: "Slovakia" },
  { city: "Ljubljana", country: "Slovenia" },
  { city: "Bled", country: "Slovenia" },
  { city: "Cape Town", country: "South Africa" },
  { city: "Johannesburg", country: "South Africa" },
  { city: "Durban", country: "South Africa" },
  { city: "Seoul", country: "South Korea" },
  { city: "Busan", country: "South Korea" },
  { city: "Jeju", country: "South Korea" },
  { city: "Barcelona", country: "Spain" },
  { city: "Madrid", country: "Spain" },
  { city: "Seville", country: "Spain" },
  { city: "Valencia", country: "Spain" },
  { city: "Granada", country: "Spain" },
  { city: "Colombo", country: "Sri Lanka" },
  { city: "Kandy", country: "Sri Lanka" },
  { city: "Stockholm", country: "Sweden" },
  { city: "Gothenburg", country: "Sweden" },
  { city: "Malmö", country: "Sweden" },
  { city: "Zurich", country: "Switzerland" },
  { city: "Geneva", country: "Switzerland" },
  { city: "Interlaken", country: "Switzerland" },
  { city: "Lucerne", country: "Switzerland" },
  { city: "Taipei", country: "Taiwan" },
  { city: "Kaohsiung", country: "Taiwan" },
  { city: "Dushanbe", country: "Tajikistan" },
  { city: "Dar es Salaam", country: "Tanzania" },
  { city: "Zanzibar", country: "Tanzania" },
  { city: "Bangkok", country: "Thailand" },
  { city: "Chiang Mai", country: "Thailand" },
  { city: "Phuket", country: "Thailand" },
  { city: "Krabi", country: "Thailand" },
  { city: "Tunis", country: "Tunisia" },
  { city: "Sousse", country: "Tunisia" },
  { city: "Istanbul", country: "Turkey" },
  { city: "Cappadocia", country: "Turkey" },
  { city: "Antalya", country: "Turkey" },
  { city: "Izmir", country: "Turkey" },
  { city: "Ashgabat", country: "Turkmenistan" },
  { city: "Kampala", country: "Uganda" },
  { city: "Kyiv", country: "Ukraine" },
  { city: "Lviv", country: "Ukraine" },
  { city: "Odesa", country: "Ukraine" },
  { city: "Dubai", country: "United Arab Emirates" },
  { city: "Abu Dhabi", country: "United Arab Emirates" },
  { city: "Sharjah", country: "United Arab Emirates" },
  { city: "London", country: "United Kingdom" },
  { city: "Manchester", country: "United Kingdom" },
  { city: "Edinburgh", country: "United Kingdom" },
  { city: "Liverpool", country: "United Kingdom" },
  { city: "Bath", country: "United Kingdom" },
  { city: "New York", country: "United States" },
  { city: "Los Angeles", country: "United States" },
  { city: "San Francisco", country: "United States" },
  { city: "Chicago", country: "United States" },
  { city: "Miami", country: "United States" },
  { city: "Las Vegas", country: "United States" },
  { city: "Seattle", country: "United States" },
  { city: "Boston", country: "United States" },
  { city: "Montevideo", country: "Uruguay" },
  { city: "Punta del Este", country: "Uruguay" },
  { city: "Tashkent", country: "Uzbekistan" },
  { city: "Samarkand", country: "Uzbekistan" },
  { city: "Caracas", country: "Venezuela" },
  { city: "Hanoi", country: "Vietnam" },
  { city: "Ho Chi Minh City", country: "Vietnam" },
  { city: "Da Nang", country: "Vietnam" },
  { city: "Hoi An", country: "Vietnam" },
  { city: "Lusaka", country: "Zambia" },
  { city: "Livingstone", country: "Zambia" },
  { city: "Harare", country: "Zimbabwe" },
  { city: "Victoria Falls", country: "Zimbabwe" },
];
